apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: prometheus 
      version: '25.16.*'
      sourceRef:
        kind: HelmRepository
        name: prometheus
        namespace: default
      interval: 60m
  values:
    server:
      persistentVolume:
        enabled: true
        size: 10Gi
        storageClass: "nfs-csi"
      replicaCount: 1
    alertmanager:
      enabled: false
