apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: promtail
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: promtail
      version: '6.15.*'
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: default
      interval: 60m
