apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: nextcloud-route
  namespace: default
spec:
  parentRefs:
  - name: bacterio-gw
  hostnames:
  - "cloud.carles.cc"
  rules:
  - backendRefs:
    - name: nextcloud
      port: 8080
    filters:
      - type: RequestHeaderModifier
        requestHeaderModifier:
          add:
            - name: X-Robots-Tag
              value: noindex,nofollow
              name: X-Permitted-Cross-Domain-Policies
              value: none
              name: Strict-Transport-Security
              value: 15552000
