apiVersion: v1
kind: Service
metadata:
  name: nextcloud-external
  namespace: default
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  externalIPs:
    - 10.9.8.15
