apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: nextcloud 
      version: '6.2.1'
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: default
      interval: 60m
  values:
    nextcloud:
      host: cloud.carles.cc
      username: admin
      password: changeme
      containerPort: 80
      #      extraVolumes:
#        - name: nfs
#          nfs:
#            server: "ofelia.carles.cc"
#            path: "/volume1/nextcloud"
#            readOnly: false
      #      extraVolumeMounts:
#  - name: nfs
#          mountPath: "/nextcloud_data"

    internalDatabase:
      enabled: false
      name: nextcloud

    externalDatabase:
      enabled: true
      ## Supported database engines: mysql or postgresql
      type: postgresql
      ## Database host. You can optionally include a colon delimited port like "myhost:1234"
      host: "10.9.8.1"
      ## Database user
      user: nextcloud
      ## Database password
      password: "nextcloud"
      ## Database name
      database: nc

  redis:
    enabled: true
    auth:
      enabled: false
      password: 'changeme'
      # name of an existing secret with Redis® credentials (instead of auth.password), must be created ahead of time
      existingSecret: ""
      # Password key to be retrieved from existing secret
      existingSecretPasswordKey: ""
    # Since Redis is used for caching only, you might want to use a storageClass with different reclaim policy and backup settings
    global:
      storageClass: "nfs-csi"
    master:
      persistence:
        enabled: true
    replica:
      persistence:
        enabled: true

  cronjob:
    enabled: true

  persistence:
    enabled: true
    storageClass: "nfs-csi"
    accessMode: ReadWriteOnce
    size: 32Gi
