apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: csi-driver-nfs
  namespace: kube-system
spec:
  interval: 10m
  chart:
    spec:
      chart: csi-driver-nfs 
      version: '4.6.*'
      sourceRef:
        kind: HelmRepository
        name: csi-driver-nfs
        namespace: default
      interval: 60m
