apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi
provisioner: nfs.csi.k8s.io
parameters:
  server: ofelia.carles.cc 
  share: /volume1/k8snfs
reclaimPolicy: Retain
volumeBindingMode: Immediate
