apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: cloud-route
  namespace: nextcloud
spec:
  parentRefs:
  - name: bacterio-gw
  hostnames:
  - "cloud.carles.cc"
  rules:
  - backendRefs:
    - name: nextcloud-aio
      port: 8080
