apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: rss-bridge
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: rss-bridge
      version: '0.5.2'
      sourceRef:
        kind: HelmRepository
        name: gabe565
        namespace: default
      interval: 60m
  values:
    persistence:
      # -- Configure persistence settings for the chart under this key.
      # @default -- See [values.yaml](./values.yaml)
      config:
        enabled: true
        retain: true
        storageClass: "nfs-csi"
        accessMode: ReadWriteOnce
        size: 2Gi
      cache:
        enabled: false
        type: emptyDir
        mountPath: /app/cache
