apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: rssbridge-route
  namespace: default
spec:
  parentRefs:
  - name: bacterio-gw
  hostnames:
  - "rss-bridge.carles.cc"
  rules:
  - backendRefs:
    - name: rss-bridge
      port: 80
