apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: jellyfin-route
  namespace: default
spec:
  parentRefs:
  - name: bacterio-gw
  hostnames:
  - "butaca.carles.cc"
  rules:
  - backendRefs:
    - name: jellyfin
      port: 8096
