apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: jellyfin 
      version: '10.8.13'
      sourceRef:
        kind: HelmRepository
        name: loeken
        namespace: default
      interval: 60m
  values:
    replicaCount: 1
    persistence:
      config:
        enabled: true
        isPvc: false
        hostPath: /home/cc250080/jellyfin/config
      cache:
        enabled: true
        isPvc: false
        hostPath: /home/cc250080/jellyfin/cache
      media:
        enabled: true
        isPvc: false
        hostPath: /home/cc250080/jellyfin/media

