apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: reloader
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: reloader
      version: '1.1.0'
      sourceRef:
        kind: HelmRepository
        name: stakater
        namespace: default
      interval: 60m
