apiVersion: v1
kind: Service
metadata:
  name: qbittorrent-service-torrent
spec:
  type: NodePort
  selector:
    app: qbittorrent
  ports:
    - protocol: UDP
      name: torrent
      port: 6881
      targetPort: 6881
      nodePort: 30007

