apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app-poc
  namespace: default
  labels:
    app: nginx
  annotations:
    reloader.stakater.com/search: "true"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "test-app-poc"
        dapr.io/app-port: "80"
        dapr.io/enable-api-logging: "true"
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
