apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: default
spec:
  interval: 10m
  chart:
    spec:
      chart: home-assistant
      version: '0.14.*'
      sourceRef:
        kind: HelmRepository
        name: gabe565
        namespace: default
      interval: 60m
  values:
    replicaCount: 1
    env:

    service:
      # -- Configures service settings for the chart.
      # @default -- See [values.yaml](./values.yaml)
      main:
        ports:
          http:
            port: 8123

    ingress:
    # -- Enable and configure ingress settings for the chart under this key.
    # @default -- See [values.yaml](./values.yaml)
      main:
        enabled: false
        # hosts:
        #   - host: chart-example.local
      #     paths:
      #       - path: /
      # tls:
      #   - secretName: chart-example.local-tls
      #     hosts:
      #       - chart-example.local

    hostNetwork: true
    dnsPolicy: ClusterFirst

    persistence:
      config:
        enabled: true
        retain: true
        storageClass: "nfs-csi"
        accessMode: ReadWriteOnce
        size: 20Gi

  # -- Enable and configure postgresql database subchart under this key.
  #    For more options see [postgresql chart documentation](https://github.com/bitnami/charts/tree/master/bitnami/postgresql)
  # @default -- Enabled (See [values.yaml](./values.yaml) for more details)
    postgresql:
      enabled: false
