apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: dapr
  namespace: dapr-system
spec:
  interval: 5m
  chart:
    spec:
      chart: dapr
      version: '1.14'
      sourceRef:
        kind: HelmRepository
        name: dapr
        namespace: default
      interval: 10m
