apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gabe656-helmrepository.yaml
  - csi-driver-nfs.yaml
  - nextcloud.yaml
  - grafana.yaml
  - prometheus-community.yaml
  - robusta.yaml
  - stakater-reloader.yaml
